/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectsea;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ryanl
 */
public class DonateGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DonateGUI.class.getName());
    private double totalRaised = 0.0;
    private double lastAmount;
    private double amount;
    private String reason;
    private final ArrayList<Double> donationAmounts = new ArrayList<>();
    private final ArrayList<String> donationReasons = new ArrayList<>();
    
    



    /**
     * Creates new form DonateGUI
     */
    public DonateGUI() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPNL = new javax.swing.JPanel();
        titleLBL = new javax.swing.JLabel();
        IMG = new javax.swing.JLabel();
        IMG2 = new javax.swing.JLabel();
        donationPNL = new javax.swing.JPanel();
        amountLBL = new javax.swing.JLabel();
        reasonLBL = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        reasonTF = new javax.swing.JTextField();
        donateBTN = new javax.swing.JButton();
        amountBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        amountTA = new javax.swing.JTextArea();
        deleteBTN = new javax.swing.JButton();
        gobckPNL = new javax.swing.JPanel();
        gobckBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPNL.setBackground(new java.awt.Color(153, 153, 153));
        headerPNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        titleLBL.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(0, 51, 204));
        titleLBL.setText("DONATION PAGE");
        titleLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout headerPNLLayout = new javax.swing.GroupLayout(headerPNL);
        headerPNL.setLayout(headerPNLLayout);
        headerPNLLayout.setHorizontalGroup(
            headerPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPNLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLBL)
                .addGap(287, 287, 287))
        );
        headerPNLLayout.setVerticalGroup(
            headerPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPNLLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(titleLBL)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        IMG.setIcon(new javax.swing.ImageIcon("C:\\Users\\ryanl\\OneDrive\\Pictures\\Screenshots\\SMALL beach clean up.png")); // NOI18N
        IMG.setText("jLabel2");

        IMG2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ryanl\\OneDrive\\Pictures\\Screenshots\\happy sea.png")); // NOI18N
        IMG2.setText("jLabel1");

        donationPNL.setBackground(new java.awt.Color(0, 51, 204));

        amountLBL.setBackground(new java.awt.Color(153, 255, 255));
        amountLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        amountLBL.setForeground(new java.awt.Color(204, 255, 255));
        amountLBL.setText("AMOUNT");

        reasonLBL.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        reasonLBL.setForeground(new java.awt.Color(204, 255, 255));
        reasonLBL.setText("REASON");

        amountTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTFActionPerformed(evt);
            }
        });

        reasonTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reasonTFActionPerformed(evt);
            }
        });

        donateBTN.setBackground(new java.awt.Color(204, 204, 204));
        donateBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        donateBTN.setText("DONATE");
        donateBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        donateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateBTNActionPerformed(evt);
            }
        });

        amountBTN.setBackground(new java.awt.Color(204, 204, 204));
        amountBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        amountBTN.setText("SEE AMOUNT RASIED ");
        amountBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        amountBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountBTNActionPerformed(evt);
            }
        });

        amountTA.setColumns(20);
        amountTA.setRows(5);
        jScrollPane1.setViewportView(amountTA);

        deleteBTN.setBackground(new java.awt.Color(204, 204, 204));
        deleteBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteBTN.setText("REMOVE DONATION");
        deleteBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout donationPNLLayout = new javax.swing.GroupLayout(donationPNL);
        donationPNL.setLayout(donationPNLLayout);
        donationPNLLayout.setHorizontalGroup(
            donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donationPNLLayout.createSequentialGroup()
                .addGroup(donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donationPNLLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(deleteBTN)
                        .addGap(105, 105, 105)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(donationPNLLayout.createSequentialGroup()
                        .addGroup(donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(donationPNLLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(reasonLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(donationPNLLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(donateBTN))
                            .addGroup(donationPNLLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(amountLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountBTN)
                            .addComponent(reasonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        donationPNLLayout.setVerticalGroup(
            donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donationPNLLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reasonLBL)
                    .addComponent(reasonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donationPNLLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountBTN)
                            .addComponent(donateBTN))
                        .addGap(18, 18, 18)
                        .addComponent(deleteBTN))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        gobckPNL.setBackground(new java.awt.Color(0, 51, 204));

        gobckBTN.setBackground(new java.awt.Color(204, 204, 204));
        gobckBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gobckBTN.setText("Go back to Infogarphic");
        gobckBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gobckBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobckBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gobckPNLLayout = new javax.swing.GroupLayout(gobckPNL);
        gobckPNL.setLayout(gobckPNLLayout);
        gobckPNLLayout.setHorizontalGroup(
            gobckPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gobckPNLLayout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(gobckBTN)
                .addGap(154, 154, 154))
        );
        gobckPNLLayout.setVerticalGroup(
            gobckPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gobckPNLLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(gobckBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(IMG, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(donationPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IMG2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(gobckPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IMG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(donationPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IMG2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gobckPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTFActionPerformed

    private void reasonTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reasonTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reasonTFActionPerformed

    private void gobckBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobckBTNActionPerformed
        // TODO add your handling code here:
        new ProjectGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gobckBTNActionPerformed

    private void donateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateBTNActionPerformed
        // TODO add your handling code here:                                          
        try {
            amount = Double.parseDouble(amountTF.getText());
            reason = reasonTF.getText();

            if (reason.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter a reason.");
                return;
            }

             // Store donation in lists
            donationAmounts.add(amount);
            donationReasons.add(reason);

            totalRaised += amount;
            amountTA.append("€" + amount + " - " + reason + "\n");

            // Clear text fields
            amountTF.setText("");
            reasonTF.setText("");
            JOptionPane.showMessageDialog(null, "Donation added, thank you so much !");
            
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid number.");
        }
        
        
        try (BufferedWriter donate = new BufferedWriter(new FileWriter("donations.txt", true))) {

        donate.write("Donation Amount: " + amount);
        donate.newLine();

        donate.write("Reason: " + reason);
        donate.newLine();

        donate.write("-------------------------------");
        donate.newLine();

        } catch (IOException e) {
        System.out.println("An error occurred: " + e);
        }


    }//GEN-LAST:event_donateBTNActionPerformed

    private void amountBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountBTNActionPerformed
        // TODO add your handling code here:
        
        amountTA.setText("Total Raised: €" + totalRaised);
    }//GEN-LAST:event_amountBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        if (donationAmounts.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No donations to delete.");
            return;
        }

        // Remove the last donation
        lastAmount = donationAmounts.remove(donationAmounts.size() - 1);
        donationReasons.remove(donationReasons.size() - 1);

        totalRaised -= lastAmount;

        // Rebuild the text area
        amountTA.setText("");
        for (int i = 0; i < donationAmounts.size(); i++) {
            amountTA.append("€" + donationAmounts.get(i) + " - " + donationReasons.get(i) + "\n");
        }

        JOptionPane.showMessageDialog(null, "Last donation removed!");
    }//GEN-LAST:event_deleteBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DonateGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMG;
    private javax.swing.JLabel IMG2;
    private javax.swing.JButton amountBTN;
    private javax.swing.JLabel amountLBL;
    private javax.swing.JTextArea amountTA;
    private javax.swing.JTextField amountTF;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton donateBTN;
    private javax.swing.JPanel donationPNL;
    private javax.swing.JButton gobckBTN;
    private javax.swing.JPanel gobckPNL;
    private javax.swing.JPanel headerPNL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel reasonLBL;
    private javax.swing.JTextField reasonTF;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
