/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectsea;

/**
 *
 * @author ryanl
 */
public class TurtleGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TurtleGUI.class.getName());

    /**
     * Creates new form TurtleGUI
     */
    public TurtleGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePNL = new javax.swing.JPanel();
        titleLBL = new javax.swing.JLabel();
        turtleIMG = new javax.swing.JLabel();
        gobackPNL = new javax.swing.JPanel();
        gobackBTN = new javax.swing.JButton();
        factsPNL = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlePNL.setBackground(new java.awt.Color(153, 153, 153));
        titlePNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        titleLBL.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(0, 51, 204));
        titleLBL.setText("TURTLE FACTS");
        titleLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout titlePNLLayout = new javax.swing.GroupLayout(titlePNL);
        titlePNL.setLayout(titlePNLLayout);
        titlePNLLayout.setHorizontalGroup(
            titlePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePNLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLBL)
                .addGap(243, 243, 243))
        );
        titlePNLLayout.setVerticalGroup(
            titlePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePNLLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(titleLBL)
                .addGap(28, 28, 28))
        );

        turtleIMG.setIcon(new javax.swing.ImageIcon("C:\\Users\\ryanl\\OneDrive\\Pictures\\Screenshots\\turtle rubish.png")); // NOI18N
        turtleIMG.setText("jLabel2");

        gobackPNL.setBackground(new java.awt.Color(0, 51, 204));

        gobackBTN.setBackground(new java.awt.Color(204, 204, 204));
        gobackBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gobackBTN.setText("Go back to Infographic");
        gobackBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gobackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gobackPNLLayout = new javax.swing.GroupLayout(gobackPNL);
        gobackPNL.setLayout(gobackPNLLayout);
        gobackPNLLayout.setHorizontalGroup(
            gobackPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gobackPNLLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(gobackBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gobackPNLLayout.setVerticalGroup(
            gobackPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gobackPNLLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(gobackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        factsPNL.setBackground(new java.awt.Color(0, 51, 204));

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("(Cool Facts About Sea Turtles)\n\n1)Sea turtles have existed for over 100 million years.\n\n2)Some species migrate thousands of miles across\n oceans every year.\n\n3)They can hold their breath for up to 7 hours\n while resting.\n\n4)Female turtles return to the exact beach they\n were born on to lay eggs — sometimes after\n decades.\n\n(How Sea Pollution Affects Sea Turtles)\n\n1)Turtles often mistake plastic bags and balloons\n for jellyfish, their favourite food, causing choking\n or starvation.\n\n2)Oil spills coat their shells, making movement,\n buoyancy, and temperature regulation difficult.\n\n3)Pollution weakens the seagrass and coral \necosystems turtles depend on.\n\n4)Entanglement in plastic rings, nets, or fishing line\n injures or traps turtles, often fatally.\n\n5)Polluted beaches make it harder for hatchlings to\n reach the sea safely.\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout factsPNLLayout = new javax.swing.GroupLayout(factsPNL);
        factsPNL.setLayout(factsPNLLayout);
        factsPNLLayout.setHorizontalGroup(
            factsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(factsPNLLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        factsPNLLayout.setVerticalGroup(
            factsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(factsPNLLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(turtleIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(factsPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(gobackPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gobackPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(turtleIMG)
                    .addComponent(factsPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gobackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackBTNActionPerformed
        // TODO add your handling code here:
        //brings you back to main infographic page 
        new ProjectGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gobackBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TurtleGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel factsPNL;
    private javax.swing.JButton gobackBTN;
    private javax.swing.JPanel gobackPNL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JPanel titlePNL;
    private javax.swing.JLabel turtleIMG;
    // End of variables declaration//GEN-END:variables
}
