/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RyanProjectSea;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ryanl
 */
public class DonateGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DonateGUI.class.getName());
    //tracks total money raised
    private double totalRaised = 0.0;
    //stores the most recent donation amount(so i can later delete)
    private double lastAmount;
    //stores user input
    private double amount;
    private String reason;
    //stores the donations
    private final ArrayList<Double> donationAmounts;
    private final ArrayList<String> donationReasons;
    
    



    /**
     * Creates new form DonateGUI
     */
    
    public DonateGUI() {
        initComponents();
        //initialize lists that stores the amountts and  reasons
        donationAmounts = new ArrayList<>();
        donationReasons = new ArrayList<>();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPNL = new javax.swing.JPanel();
        titleLBL = new javax.swing.JLabel();
        donationPNL = new javax.swing.JPanel();
        amountLBL = new javax.swing.JLabel();
        reasonLBL = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        reasonTF = new javax.swing.JTextField();
        donateBTN = new javax.swing.JButton();
        amountBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        amountTA = new javax.swing.JTextArea();
        deleteBTN = new javax.swing.JButton();
        gobckPNL = new javax.swing.JPanel();
        gobckBTN = new javax.swing.JButton();
        happysesaIMG = new javax.swing.JLabel();
        beachCleanUpMG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPNL.setBackground(new java.awt.Color(153, 153, 153));
        headerPNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        titleLBL.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(0, 51, 204));
        titleLBL.setText("DONATION PAGE");
        titleLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout headerPNLLayout = new javax.swing.GroupLayout(headerPNL);
        headerPNL.setLayout(headerPNLLayout);
        headerPNLLayout.setHorizontalGroup(
            headerPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPNLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLBL)
                .addGap(287, 287, 287))
        );
        headerPNLLayout.setVerticalGroup(
            headerPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPNLLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(titleLBL)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        donationPNL.setBackground(new java.awt.Color(0, 51, 204));

        amountLBL.setBackground(new java.awt.Color(153, 255, 255));
        amountLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        amountLBL.setForeground(new java.awt.Color(204, 255, 255));
        amountLBL.setText("AMOUNT :");

        reasonLBL.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        reasonLBL.setForeground(new java.awt.Color(204, 255, 255));
        reasonLBL.setText("REASON AND NAME :");

        amountTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTFActionPerformed(evt);
            }
        });

        reasonTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reasonTFActionPerformed(evt);
            }
        });

        donateBTN.setBackground(new java.awt.Color(204, 204, 204));
        donateBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        donateBTN.setText("DONATE");
        donateBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        donateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateBTNActionPerformed(evt);
            }
        });

        amountBTN.setBackground(new java.awt.Color(204, 204, 204));
        amountBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        amountBTN.setText("SEE AMOUNT RASIED ");
        amountBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        amountBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountBTNActionPerformed(evt);
            }
        });

        amountTA.setColumns(20);
        amountTA.setRows(5);
        jScrollPane1.setViewportView(amountTA);

        deleteBTN.setBackground(new java.awt.Color(204, 204, 204));
        deleteBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteBTN.setText("REMOVE DONATION");
        deleteBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout donationPNLLayout = new javax.swing.GroupLayout(donationPNL);
        donationPNL.setLayout(donationPNLLayout);
        donationPNLLayout.setHorizontalGroup(
            donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donationPNLLayout.createSequentialGroup()
                .addGroup(donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donationPNLLayout.createSequentialGroup()
                        .addGroup(donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(donationPNLLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(reasonLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(donationPNLLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(amountLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reasonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(donationPNLLayout.createSequentialGroup()
                        .addGroup(donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(donationPNLLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(deleteBTN))
                            .addGroup(donationPNLLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(donateBTN)
                                .addGap(44, 44, 44)
                                .addComponent(amountBTN)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)))
                .addContainerGap())
        );
        donationPNLLayout.setVerticalGroup(
            donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donationPNLLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reasonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reasonLBL))
                .addGroup(donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donationPNLLayout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(donationPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountBTN)
                            .addComponent(donateBTN))
                        .addGap(18, 18, 18)
                        .addComponent(deleteBTN)
                        .addGap(22, 22, 22))
                    .addGroup(donationPNLLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        gobckPNL.setBackground(new java.awt.Color(0, 51, 204));

        gobckBTN.setBackground(new java.awt.Color(204, 204, 204));
        gobckBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gobckBTN.setText("Go back to Infogarphic");
        gobckBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gobckBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobckBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gobckPNLLayout = new javax.swing.GroupLayout(gobckPNL);
        gobckPNL.setLayout(gobckPNLLayout);
        gobckPNLLayout.setHorizontalGroup(
            gobckPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gobckPNLLayout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(gobckBTN)
                .addGap(154, 154, 154))
        );
        gobckPNLLayout.setVerticalGroup(
            gobckPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gobckPNLLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(gobckBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        happysesaIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RyanProjectSea/happy sea.png"))); // NOI18N
        happysesaIMG.setText("jLabel1");

        beachCleanUpMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RyanProjectSea/SMALL beach clean up.png"))); // NOI18N
        beachCleanUpMG.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beachCleanUpMG, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donationPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(happysesaIMG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gobckPNL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(beachCleanUpMG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(donationPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(happysesaIMG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gobckPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTFActionPerformed

    private void reasonTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reasonTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reasonTFActionPerformed

    private void gobckBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobckBTNActionPerformed
        // TODO add your handling code here:
        
        //brings you back to the main infographic page
        new ProjectGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gobckBTNActionPerformed

    private void donateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateBTNActionPerformed
        // TODO add your handling code here:                                          
        try {
            //convert the amount text to a nunber
            amount = Double.parseDouble(amountTF.getText());
            reason = reasonTF.getText();
            
            //validates the reason
            if (reason.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter a reason.");
                return;
            }

             // Store new donation in memory
            donationAmounts.add(amount);
            donationReasons.add(reason);
            
            //update total amount
            totalRaised += amount;
            //shows donation in the text area
            amountTA.append("€" + amount + " - " + reason + "\n");

            // Clears users input after donation in made
            amountTF.setText("");
            reasonTF.setText("");
            JOptionPane.showMessageDialog(null, "Donation added, thank you so much !");
            
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid number.");
        }
        
        //saves donation to file
        try (BufferedWriter donate = new BufferedWriter(new FileWriter("donations.txt", true))) {
            
        //wrtie the donation amount to file
        donate.write("Donation Amount: " + amount);
        donate.newLine();//moves onto the next line in the file

        //writes the reason to file and moves onto next line
        donate.write("Reason: " + reason);
        donate.newLine();
        
        //i added a seperater line to make the donations easier to read 
        donate.write("-------------------------------");
        donate.newLine();

        } catch (IOException e) {
            //if there is an error print the reason 
        System.out.println("An error occurred: " + e);
        }


    }//GEN-LAST:event_donateBTNActionPerformed

    private void amountBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountBTNActionPerformed
        // TODO add your handling code here:
        
        //shows only the total a ount raised 
        amountTA.setText("Total Raised: €" + totalRaised);
    }//GEN-LAST:event_amountBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        //if no donation has been added stop this method 
        if (donationAmounts.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No donations to delete.");
            return;
        }

        // Remove the last donation
        lastAmount = donationAmounts.remove(donationAmounts.size() - 1);
        donationReasons.remove(donationReasons.size() - 1);
        
        //subtract the most recent donation amount from total raised 
        totalRaised -= lastAmount;

        // clear display and rebuilt the lsit of donations 
        amountTA.setText("");
        //loops through all remaining donations after one is deleted 
        for (int i = 0; i < donationAmounts.size(); i++) {
            //readds each donation to the text area
            amountTA.append("€" + donationAmounts.get(i) + " - " + donationReasons.get(i) + "\n");
        }

        JOptionPane.showMessageDialog(null, "Last donation removed!");
        
    }//GEN-LAST:event_deleteBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DonateGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton amountBTN;
    private javax.swing.JLabel amountLBL;
    private javax.swing.JTextArea amountTA;
    private javax.swing.JTextField amountTF;
    private javax.swing.JLabel beachCleanUpMG;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton donateBTN;
    private javax.swing.JPanel donationPNL;
    private javax.swing.JButton gobckBTN;
    private javax.swing.JPanel gobckPNL;
    private javax.swing.JLabel happysesaIMG;
    private javax.swing.JPanel headerPNL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel reasonLBL;
    private javax.swing.JTextField reasonTF;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
